export const router_Second = "pages/ViewController/Second"

export const router_Home = "pages/ViewController/Home"

export const router_LoginViewController = "pages/ViewController/Login/LoginViewController"

export const router_Index = "pages/Index"

export const router_SMSViewController = "pages/ViewController/Login/SMSViewController"

export const router_CreateDocumentPage1 = "pages/ViewController/Document/CreateDocumentPage1"

export const router_AccountViewController = "pages/ViewController/Account/AccountViewController"

export const router_EvalutionViewController = "pages/ViewController/Evalution/EvalutionViewController"

export const router_VIPPurchaseViewController = "pages/ViewController/VIP/VIPPurchaseViewController"

export const router_ServiceViewController = "pages/ViewController/Account/ServiceViewController"

export const router_DocumentListPage = "pages/ViewController/Document/DocumentListPage"

export const router_DDCustomizedViewController = "pages/ViewController/Train/DDCustomizedViewController"

export const router_DDTrainHomeViewController = "pages/ViewController/Train/DDTrainHomeViewController"
